#! /bin/sh

# mount /proc and /sys
/bin/mount -a

# mkdir -p /dev
# /bin/mount -t devtmpfs devtmpfs /dev

# print information
echo "-------------------------------------------" > /dev/console
echo "Starting pfetch...\n" > /dev/console
/bin/pfetch > /dev/console

# step in shell 
echo "-------------------------------------------" > /dev/console
echo "Starting bash...\n" > /dev/console

echo "System time: $(date)" > /dev/console
echo "Current user: $USER" > /dev/console
echo "Current directory: $(pwd)\n" > /dev/console